version: 2
project_name: web2mail

builds:
  - id: web2mail
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - 7
    binary: web2mail
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}

archives:
  - name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    format_overrides:
      - goos: windows
        formats: [zip]

nfpms:
  - id: web2mail
    package_name: web2mail
    formats:
      - deb
      - rpm
      - apk
      - archlinux
    maintainer: Faisal <faisal@example.com>
    description: A webhook to SMTP/Sendmail bridge specifically for forwardemail.net to deliver emails via an HTTP reverse proxy like nginx or cloudflared
    license: MIT

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ .Version }}-snapshot"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
